local_host:
    dataset: 'tank/localexample'
    retain: 3

remote_host:
    host_setup:
        host: 172.27.6.148 # IP or hostname, no quotation marks
        #these are defaulted to 22, root and /root/.ssh/id_rsa respectively;
        #they can remain commented unless you actually need to change them
        #port: 
        #user:
        #ssh_key: 
    dataset: 'tank/remoteexample'
    retain: 10

snapshot_information:
    incremental: True|False
    type_snapshot: True|False 
