
#
# Log configuration
#
logging:
    version: 1
    formatters:
        simpleFormater:
            format: '%(asctime)s - %(levelname)s: %(message)s'
            datefmt: '%Y/%m/%d %H:%M:%S'
    
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormater
            level: DEBUG
            stream: ext://sys.stdout
        file:
            class : logging.FileHandler
            formatter: simpleFormater
            level: WARNING
            filename: /home/econnors/gitstuff/zfs-replicate/log/replicator.log
    
    loggers:
        replicator_log:
            level: DEBUG
            handlers: [console, file]



                
